{
    'name': "Mstech Jasatec2",
    "category": "Sale Renting",
    'author': "Meditech",
    'summary':"Mstech Jasatec2",
    'depends': [
    	'mstech_jasatec1',
        'sale_renting',
        'sale_stock_renting',
        'industry_fsm',
        'industry_fsm_sale',

    ],
    'data': [
        'data/project_data.xml',
        'views/project_views.xml',
        'views/view_project_task.xml',
        'views/report_jasatec_contract.xml',
        'views/account_move_view.xml',
        'views/sale_order_views.xml',
        'report/report_sale_contract.xml',
        'report/report_sale_arrendamiento.xml',
        'report/report_sale_order.xml',
        'report/report_project_task.xml',
        'report/project_task_report.xml',
    ],
    'installable' : True,
    'auto_install' :  False,
    'application' :  False,
}
